### ISSUE TITLE
Error starting the analysis

### ISSUE THREAD

**Issue by cli0** [hgascon/adagio#12]
Hello, I want to use Adagio to do some call graphs analysis and I run the following command:

```$ ./adagio.py -f -d clean_dir/```

The directory `clean_dir/` contains a couple of benign .apk files. But I always get the following errors:

```Processing 3 APK files in dir clean_dir/
[] Loading /datadisk/Workspace/adagio/clean_dir/waze.apk                             ] ETA:  --:--:-- 
[*] NameError error loading /datadisk/Workspace/adagio/clean_dir/waze.apk
[] Loading /datadisk/Workspace/adagio/clean_dir/com.android.vending_10.6.08-all_0_PR_200628961-81060800_minAPI16_apkmirror.com.apk
[*] NameError error loading /datadisk/Workspace/adagio/clean_dir/com.android.vending_10.6.08-all_0_PR_200628961-81060800_minAPI16_apkmirror.com.apk
[] Loading /datadisk/Workspace/adagio/clean_dir/com.google.android.music_8.13.7350-3.G-73503_minAPI21_apkmirror.com.apk
[*] NameError error loading /datadisk/Workspace/adagio/clean_dir/com.google.android.music_8.13.7350-3.G-73503_minAPI21_apkmirror.com.apk
Building graphs: 100% [###############################################################################] Time: 0:00:00 
Done.
```

I tried cleaning up the names to something very simple like the first .apk named waze.apk but I still get the name error. Can you help me with this error message? Am I doing something wrong when instantiating the process?

**Comment by Asbatel** [comment]
I'm having the same error, any help?

**Comment by hgascon** [comment]
I have updated the dependencies so it is not necessary to clone androguard in modules/ anymore. You can install androguard with pip and it will be directly imported. Some of the exceptions were due to refactoring introduced in the last versions of androguard. I expect this to be fixed now.
