### ISSUE TITLE
Have some problems

### ISSUE THREAD

**Issue by Sp1keeeee** [hgascon/adagio#15]
Hi,dear hgascon,I have some problems when I use adagio.
First,I use adagio.py but the output files are not end with fcg.But in adagio.core.Analysis.read_files,it only can deal with files end with fcg.
Second,I add fcg extension to the files but it gots some erro:

a = Analysis(["benign/","malware/"],labels=[1,0],split=0.8)
Loading samples in dir benign/ with label 1
  0%|          | 0/2 [00:00<?, ?it/s]'DiGraph' object has no attribute 'neighbors_iter'
err: benign/b3d5166e6dccd4f81d8409582dba5cad3b58b78540ebfe8475a5e90823148335.fcg
.
.
.

Every files have this erro,how can i fix it?

And what the python version is?

Thank u very much if u can give me some help!

**Comment by zhangchennan** [comment]
I have fix the second problem by install networkx(version == 1.9)
But i got some new problems:
![image](https://user-images.githubusercontent.com/33228682/111780774-d01da900-88f2-11eb-97e4-84ca1565ba72.png)

**Comment by zhangchennan** [comment]
I have succeed to run it by change some codes,but androguard have some problems to extract instructions.

**Comment by hgascon** [comment]
Feel free to send a PR.  What exactly is the problem with androguard?

**Comment by zhangchennan** [comment]
Well,in graphs.py,in line 53 
`ops = n.get_instructions()`
this function did not work at sometimes and it causes encoded_label to be a string object.
So I need to run it to add code like:
![image](https://user-images.githubusercontent.com/33228682/112713276-5b102c00-8f0f-11eb-9f77-92462fd15265.png)
And I have changed line 335 in analysis.py 
![image](https://user-images.githubusercontent.com/33228682/112713401-b8a47880-8f0f-11eb-83b8-0031bb2991f2.png)
max_iter=55000,it will have warning "ConvergenceWarning: Liblinear failed to converge, increase the number of iterations..."

**Comment by hgascon** [comment]
I think that `encoded_label` being a string wasn't the issue and the `max_iter` parameter seems to be problem dependent. Maybe you can parameterise this?

**Comment by zhangchennan** [comment]
OK,anyway,thanks for ur help！

**Comment by zhangchennan** [comment]
OK,thanks for ur help!
