### ISSUE TITLE
How to run this project ?

### ISSUE THREAD

**Issue by 562526772** [hgascon/adagio#5]
I have installed all the dependencies and can start the project by "adagio.py".
But when I finished this command and use iPython as http://adagio.readthedocs.org/ said, I found problems at first step. 
Could you give a updated introduction to tell us how to run this project ?

**Comment by 562526772** [comment]
When I imput the command "from adagio.core.analysis import Analysis", it says "no modual named pybloom". How to solve it ?

**Comment by hgascon** [comment]
You can comment the import and the “bloom_filter_hash” function. ml.py is a helping module with different related functions but not all of them are necessarily used.
