### ISSUE TITLE
How to implement androguard for adagio?

### ISSUE THREAD

**Issue by Choosue** [hgascon/adagio#7]
I have put the androguard main folder into "modules" folder of adagio, while I couldn't make adagio run because I got the error "ImportError: No module named androguard.androlyze"

So what is the correct way to import androguard? from my knowledge, there is no way to install androguard from python pip. BTW, since the [google code site](https://code.google.com/p/androguard/) was abandoned by androguard team, the only way to download androguard is throug [Github](https://github.com/androguard/androguard).

**Comment by hgascon** [comment]
Hi @Choosue, actually, it is possible now to install androguard from pip. That means that there is no need to clone androguard in modules/ anymore. I should also change the imports it in all modules. You can try it and submit a pull request if you like.

**Comment by Choosue** [comment]
Thanks

I've copied "__init__.py" and "__init__.pyc" file to the modules/androguard
folder, and it makes sense



2017-02-23 21:40 GMT+08:00 Hugo Gascón <notifications@github.com>:

**Comment by Choosue** [comment]
Yes, it is possible now to install androguard from pip: `python -m pip install androguard`

But I still cannot change all the imports in adagio. Here is why:

There are two files import androguard:
`from modules.androguard.androlyze import *` in adagio/core/graphs.py
and
`from modules.androguard import *
from modules.androguard.androguard.core.analysis import *
from modules.androguard.androlyze import *` in adagio/core/apicalls.py

for you only imports * from androguard module, and I am not familiar with androguard
I got no idea how to replace them...

**Comment by bingoxia** [comment]
why ?
[*] NameError error loading /home/bingo/桌面/adagio-master/test/021d55c415ff951c8e7b1ce3f94399bb.apk.1

**Comment by hgascon** [comment]
@bingoxia can you be more specific with the error?

**Comment by hgascon** [comment]
@bingoxia did you solve this? Can it be a problem with the chinese characters in the file path?

**Comment by JunTomyang** [comment]
@hgascon @bingoxia Hi guys, I have also involved the same problem and no FCG was generated: 

Processing 3 APK files in dir APK_DATA/
[] Loading /home/nsclab/Desktop/adagio/APK_DATA/0a1f17846f67d57d357ec458e3ced59a.apk
[*] NameError error loading /home/nsclab/Desktop/adagio/APK_DATA/0a1f17846f67d57d357ec458e3ced59a.apk
[] Loading /home/nsclab/Desktop/adagio/APK_DATA/000a067df9235aea987cd1e6b7768bcc1053e640b267c5b1f0deefc18be5dbe1.apk
[*] NameError error loading /home/nsclab/Desktop/adagio/APK_DATA/000a067df9235aea987cd1e6b7768bcc1053e640b267c5b1f0deefc18be5dbe1.apk
[] Loading /home/nsclab/Desktop/adagio/APK_DATA/15640e3e6896f2222c299a3ad4ffe2b6e854eefd67264b76b93551831403410b.apk
[*] NameError error loading /home/nsclab/Desktop/adagio/APK_DATA/15640e3e6896f2222c299a3ad4ffe2b6e854eefd67264b76b93551831403410b.apk
Building graphs: 100% [#########################################] Time: 0:00:02 
Done.


Could you please give me some advice, thanks

**Comment by hgascon** [comment]
@JunTomyang that might be a problem with the handling of the file path.

**Comment by JunTomyang** [comment]
@hgascon Hi hgascon , I have changed the file path without underscore but the error still cannot fix:

Processing 3 APK files in dir APK_DATA/
[] Loading /home/nsclab/Desktop/adagio/APK/0a1f17846f67d57d357ec458e3ced59a.apk
[] NameError error 
[] Loading /home/nsclab/Desktop/adagio/APK/000a067df9235aea987cd1e6b7768bcc1053e640b267c5b1f0deefc18be5dbe1.apk
[] Loading /home/nsclab/Desktop/adagio/APK/15640e3e6896f2222c299a3ad4ffe2b6e854eefd67264b76b93551831403410b.apk
[*] NameError error 
Building graphs: 100% [#########################################] Time: 0:00:02
Done.

**Comment by hgascon** [comment]
@JunTomyang are you giving "APK/" as parameter? Can you try without the "/"?

**Comment by Asbatel** [comment]
I run the following command: ./adagio.py -f -d apks    (with apks is the dir that contains apks). I got that error: NameError error loading /home/le/adagio//apks/hello.apk

Any help please!

**Comment by hgascon** [comment]
I have update the dependencies. It not necessary to clone androguard in modules/ anymore. You can install androguard with pip and it will be directly imported. Let me know how it works.
