### ISSUE TITLE
How to compute aggregated weight of each bin of the histogram?

### ISSUE THREAD

**Issue by Choosue** [hgascon/adagio#8]
In your [paper](http://user.informatik.uni-goettingen.de/~hgascon/docs/2013b-aisec.pdf)

you've mentioned in section 2.4 that:

> In order to identify what substructures of Gh contribute
to this decision, it is necessary to reverse the expansion performed
in Eq. (5). In particular, we compute an aggregated
weight ˆwi for each bin i of the histogram (corresponding to
the i hash value of the graph Gh). Formally, this is achieved
for the i-th bin of the histogram as follows
![qq 20170312102045](https://cloud.githubusercontent.com/assets/6078821/23828472/9807091e-070d-11e7-83dd-d988c3b9e95b.jpg)

But I still don't know how to compute this aggregated weigtht

Could you please explain it in details?

**Comment by Choosue** [comment]
In addition

In adagio/core/analysis.py, there is a function called "get_high_ranked_neighborhoods"

But it seems that we can get the "sorted_weights_idx" parameter from no where

**Comment by hgascon** [comment]
The weights are part of the model learnt by the linear SVM. As the doc string in the function says:
```
:param sorted_weights_idx: index that sort the weights from the  linear classifier
```
That requires you to get the weights of the linear SVM classifier object and sort them accordingly. For instance by doing:
```
 w = numpy.argsort(sklearn.svm.LinearSVC.coef_)
```

**Comment by PegX** [comment]
Hi Hugo, here i also have a little bit confused.
Of course, i totally understand the way to get the sorted weight through w = numpy.argsort(sklearn.svm.LinearSVC.coef_). It seems using the sort function for the learned weights which are getting by coef_ variable of linear SVC. However, the dimension of this weights is (2**15)*MAX. And using this learned weights we can get the aggregated weight. 
So my confused point is should we utilize the aggregated weight to get the high_ranked_neighborhoods or get using the trained weights to get it.  Just like what you described in this statement: w = numpy.argsort(sklearn.svm.LinearSVC.coef_). It seems using the learnt weight to get the high_ranked_neighborhoods. And then what is the really contribution of aggregated weight in Adagio?

**Comment by hgascon** [comment]
The weights W have (2**15)*M dimensions. So the weights of the neighborhoods are given by
```W.reshape(2**15, M).sum(axis=1)```
